image: registry.gitlab.com/christiantragesser/pypline-ci:3

variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375

services:
  - name: docker:stable-dind
    command: ["--registry-mirror=https://dockerhub-mirror0.artifactory.asynchrony.com"]

stages:
  - test

test:
  stage: test
  script:
    - docker build -t $CI_REGISTRY/christiantragesser/clair-scan-util:latest .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY/christiantragesser/clair-scan-util:latest | grep -e "The push refers to" -e latest
